# This is a basic workflow to help you get started with Actions
 
name:
  Automated cronjob workflow
 
# Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  workflow_dispatch 
  # schedule:
  #  - cron: "*/15 * * * *"
  
permissions: write-all
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v4

      - name: get current date
        id: date
        run: echo "{date}={$(date +'%Y-%m-%d')}" >> $DATE_TEST
        
      - name: commit
        run: |
          date > mystrongfiles/$DATE_TEST.txt
          git config user.name octopi291
          git config user.email octopi291@gmail.com
          git add .
          git commit -m "commit-${{ steps.date.outputs.date }}"
          git push
